appId: jp.laf.hiro
productName: 'LaF'
win:
  artifactName: ${productName}_${version}_portable_${os}_${arch}.${ext}
  target:
    - target: nsis
      arch:
        - x64
        - ia32
    - target: portable
      arch:
        - x64
        - ia32
linux:
  artifactName: ${productName}_portable_${os}_${arch}.${ext}
  target:
    - target: appImage
      arch:
        - x64
        - ia32
  category: game
nsis:
  artifactName: ${productName}_${version}_installer_${os}_${arch}.${ext}
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true